const insults = [
  "kamu jelek kak wkwkw",
  "ayo mandi, bau!",
  "haduuh, gak guna deh",
  "nemu cowok baru? pasti plastik lagi",
  "udah, stop selfie aja, gak banget",
  "ngomong terus, males denger",
  "muka mu kaya tempat parkir truk",
  "bebek aja lebih keren dari kamu",
  "otak kera, otak udang, sama aja",
  "jomblo mulu, gak laku",
  "inget mandi, mandinya pake air, ya",
  "gak usah senyum, serem aja",
  "gak ada kerjaan ya, sampe sini",
  "bodoh banget, serius",
  "tahi lalat mu mirip butiran nasi",
  "cermin diri dulu deh sebelum menghina",
  "diem aja gak usah ngomong",
  "pinternya cuma omong doang",
  "tangan mu kotor terus",
  "ngomong jorok terus, gak sopan",
  "gak ada rasa malu ya, haduh",
  "debat sama kamu kaya debat sama batu",
  "apa sih yang berguna dari hidupmu?",
  "mau jadi apa, ya? gak punya skill",
  "anak umur segini masih cupu",
  "duh, sebel deh sama kamu",
  "cape deh dengerin kamu",
  "gak usah ngerayu, gak bakal berhasil",
  "baju kaya gini siapa yang mau?",
  "gak ada otak, huh?",
  "gak ada pikiran, pikirin dulu",
  "buka mata lebar-lebar, ya",
  "ngomong terus, ngeselin",
  "fisikmu gak menarik, maaf ya",
  "ada selera gak sih sama makanan?",
  "sadar gak sih, gak punya bakat",
  "gak usah sok keren, ya",
  "gak usah pamer apa yang gak punya",
  "gak punya kerjaan ya, mending tidur",
  "terus terang, gak suka sama kamu",
  "sayangnya kamu gak berguna",
  "gak ada keistimewaan sama sekali",
  "maaf, kamu itu nol besar",
  "gak ada obat buat gak jomblo",
  "ternyata otak udang gak mati-mati",
  "punya masalah, cerita ke kantong aja",
  "gak punya teman ya, susah deh",
  "gak usah banyak alasan, malas dengernya",
  "pinternya cuma bawa gosip doang",
  "kepo banget sama hidup orang",
  "serius deh, kamu gak penting",
];
module.exports = { insults }